#!/bin/bash
set -eo pipefail

branch=$(git branch --show-current)
if [ "$branch" = "main" ] || [ "$branch" = "preview" ]; then
  echo "ERROR: Direct commits to $branch branch are not allowed."
  echo "Create a feature branch instead."
  exit 1
fi

bun run check &
check_pid=$!
bun run build &
build_pid=$!

wait $check_pid || exit_status=$?
wait $build_pid || exit_status=$?

if [ -n "$exit_status" ]; then
  exit 1
fi
